before_script:
   - apt-get update -qy
   - apt-get install -y python3-dev python3-pip

stages:
  - test

test:
  stage: test
  image: python:3.6-buster
  script:
  - pip3 install -r requirements.txt
  - python3 test.py
