stages:
  - unittests
  - main

unittest_minion:
  stage: unittests
  image: python:3.6-buster
  script:
  - pip3 install -r requirements.txt
  - nosetests tests/test_minion.py

unittest_player:
  stage: unittests
  image: python:3.6-buster
  script:
  - pip3 install -r requirements.txt
  - nosetests tests/test_player.py

main:
  stage: main
  image: python:3.6-buster
  script:
  - pip3 install -r requirements.txt
  - python3 main.py
