before_script:
   - apt-get update -qy
   - apt-get install -y python3-dev python3-pip

stages:
  - test_1804
  - test_2004
  - test_buster

test_1804:
  stage: test_1804
  image: ubuntu:18.04
  script:
  - pip3 install -r requirements.txt
  - python3 test.py

test_2004:
  stage: test_1804
  image: ubuntu:20.04
  script:
  - pip3 install -r requirements.txt
  - python3 test.py

test_buster:
  stage: test_buster
  image: python:3.8-buster
  script:
  - pip3 install -r requirements.txt
  - python3 test.py
